version: '3.8'

services:
  backend:
    image: thisyannhallage/cloudsaasapp-server:latest
    ports:
      - "3000:3000"
    env_file:
      - ./serverwave/.env

  frontend:
    image: thisyannhallage/cloudsaasapp-front:latest
    ports:
      - "4173:4173"
    depends_on:
      - backend


# jqjjq
