version: '3.8'

services:
  backend:
    image: cloudsaasapp-serverlatest
    ports:
      - "3000:3000"
    env_file:
      - ./serverwave/.env

  frontend:
    image: cloudsaasapp-front:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
